<a class="homepage_link" href="/">
    <img src="/src/public/assets/images/circle_left.svg">
</a>
<div class="container">
    <div class="title">Mitarbeiter</div>
    <a class="add_employee" href="/employees/add-employee/">Mitarbeiter hinzufügen</a>
    <div class="table">
        <div class="table_filter_row">
            <input class="table_filter_firstname" type="text" placeholder="Vorname">
            <input class="table_filter_lastname" type="text" placeholder="Nachname">
            <select class="table_filter_job">
                <option value="0">Alle Berufe</option>
                <?php foreach ($assigns['jobs'] as $job): ?>
                    <option value="<?= $job['job_id'] ?>"><?= $job['job_name'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="table_column_type_row">
            <div>Vorname</div>
            <div>Nachname</div>
            <div>Beruf</div>
            <div>Optionen</div>
        </div>
        <?php
        if ($assigns['employeeList'] !== null):
            foreach ($assigns['employeeList'] as $employee): ?>
                <div class="table_entry" data-job-id="<?= $employee['employee_job_id'] ?>">
                    <div class="table_entry_firstname"><?= $employee['employee_firstname'] ?></div>
                    <div class="table_entry_lastname"><?= $employee['employee_lastname'] ?></div>
                    <div class="table_entry_job_name"><?= $employee['employee_job_name'] ?></div>
                    <div class="table_entry_options">
                        <img title="Bearbeiten" src="/src/public/assets/images/EditBlue.svg" onclick="javascript:window.location='/employees/edit-employee/?employeeID=<?=$employee['employee_id']?>';">
                        <img title="Löschen" src="/src/public/assets/images/Remove.svg" onclick="javascript:window.location='/employees/delete-employee/?employeeID=<?=$employee['employee_id']?>';">
                    </div>
                </div>
            <?php endforeach;
        endif; ?>
    </div>
</div>