<div class="container">
    <div class="title">Projekt Manager</div>
    <div class="redirect_container">
        <?php if (!array_key_exists('user', $_SESSION)): ?>
            <a class="redirect_login" href="/login/">Login</a>
        <?php else: ?>
            <a class="redirect_login" href="/logout/">Logout</a>
        <?php endif; ?>
        <a class="redirect_employees" href="/employees/">Mitarbeiter</a>
        <a class="redirect_projects" href="/projects/">Projekte</a>
    </div>
</div>